Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,11 +4,25 @@ on:
   pull_request:
     branches:
       - main
+  workflow_dispatch: # Permite rodar manualmente a pipeline
 
 jobs:
   build:
     runs-on: ubuntu-latest
-
+    services:
+      postgres:
+        image: postgres:17
+        ports:
+          - 5432:5432
+        env:
+          POSTGRES_DB: ${{ secrets.DB_SCHEMA }}
+          POSTGRES_USER: ${{ secrets.DB_USER }}
+          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
+        options: >-
+          --health-cmd="pg_isready -U postgres"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=5
     steps:
       # Checkout do código
       - name: Checkout code
@@ -21,26 +35,32 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      # Limpar o cache do Maven
-      - name: Clear Maven cache
-        run: mvn dependency:purge-local-repository
-
       # Cache do Maven para acelerar builds
       - name: Cache Maven dependencies
         uses: actions/cache@v3
         with:
           path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ github.run_id }}
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-m2
 
+      # Esperar o banco de dados estar pronto
+      - name: Wait for Postgres
+        run: |
+          for i in {1..10}; do
+            nc -z localhost 5432 && echo "Postgres is up!" && exit 0
+            echo "Waiting for Postgres..."
+            sleep 5
+          done
+          echo "Postgres failed to start" && exit 1
+
       # Rodar o Maven para verificar e gerar o relatório de cobertura
       - name: Run tests and generate coverage report
-        run: mvn clean verify -U
+        run: mvn clean verify
 
       # Publicar o relatório de cobertura como artefato
       - name: Upload coverage report
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v3
         with:
           name: jacoco-coverage-report
           path: target/site/jacoco-merged-test-coverage-report
